use crate::schema::Document;
use std::io::Write;

/// A response to a client statement.
///
/// This is generated by the [`frontend`], then serialized by
/// this module to be sent over the network to the client.
///
/// [`frontend`]: crate::frontend
pub enum Response {
    Opened,
    Acquired,
    Selected,
    Document(Document),
}

impl Response {
    /// Write the serialized [`Response`] to a [`Write`].
    pub fn serialize(self, mut out: impl Write) -> Result<(), std::io::Error> {
        match self {
            Response::Opened => writeln!(out, "(ok opened)")?,
            Response::Acquired => writeln!(out, "(ok acquired)")?,
            Response::Selected => writeln!(out, "(ok selected)")?,
            Response::Document(doc) => {
                let write_result = doc.into_writer(out.by_ref());
                if let Err(error) = write_result {
                    writeln!(out, "Serialization error: {}", error)?;
                }
                writeln!(out)?;
            }
        }
        Ok(())
    }
}
